In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv('data/data_set.csv')

In [3]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
# DEfine independent(X) and dependent(y) feature 
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [5]:
X

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation

In [6]:
y

0             Normal_Weight
1             Normal_Weight
2             Normal_Weight
3        Overweight_Level_I
4       Overweight_Level_II
               ...
2106       Obesity_Type_III
2107       Obesity_Type_III
2108       Obesity_Type_III
2109       Obesity_Type_III
2110       Obesity_Type_III
Name: NObeyesdad, Length: 2111, dtype: object

In [7]:
# Define categorical and numerical columns
cat_cols = X.select_dtypes(include='O').columns
num_cols = X.select_dtypes(exclude='O').columns

In [8]:
cat_cols

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS'],
      dtype='object')

In [9]:
num_cols

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')

In [10]:
# import sklearn packages for data treatments

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# import sklearn model

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# import metrics

from sklearn.metrics import accuracy_score ,classification_report

In [11]:
# train test split

X_train , X_test,y_train,y_test=train_test_split(X,y,test_size = 0.3 , random_state=40)

In [12]:
X_train

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
1661,Male,22.832105,1.867140,121.835883,yes,yes,2.826251,2.604998,Sometimes,no,1.842173,no,1.284798,0.000000,Sometimes,Public_Transportation
715,Male,17.000000,1.844749,59.313525,yes,yes,2.432886,3.000000,Sometimes,no,2.000000,no,2.697949,1.000000,no,Automobile
1257,Male,18.000000,1.820930,108.742005,yes,yes,2.000000,1.255350,Sometimes,no,2.497065,no,1.000000,1.441605,no,Public_Transportation
1737,Male,25.659092,1.848420,117.631707,yes,yes,2.128574,3.000000,Sometimes,no,2.531984,no,1.003294,0.026575,Sometimes,Public_Transportation
829,Female,21.198217,1.743841,78.880360,yes,yes,2.510583,1.000000,Sometimes,no,2.000000,no,2.119682,0.000000,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.000000,3.000000,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation
626,Male,17.377131,1.811238,58.830710,yes,yes,2.483979,3.762778,Sometimes,no,2.000000,no,2.000000,0.930051,no,Automobile
1863,Female,19.176140,1.666194,124.805868,yes,yes,3.000000,3.000000,Sometimes,no,1.228838,no,0.792553,0.639561,Sometimes,Public_Transportation
1330,Female,24.317607,1.586751,79.109029,yes,yes,2.000000,1.000000,Sometimes,no,2.000000,no,0.852446,0.000000,no,Public_Transportation
2055,Female,25.962949,1.623812,109.996742,yes,yes,3.000000,3.000000,Sometimes,no,2.395387,no,0.000272,0.461532,Sometimes,Public_Transportation

In [13]:
X_test

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
1791,Male,24.001889,1.614075,100.245302,yes,yes,2.880483,1.703299,Sometimes,no,1.006378,no,1.076729,1.058007,no,Public_Transportation
519,Female,18.535075,1.688025,45.000000,no,yes,3.000000,3.000000,Sometimes,no,3.000000,yes,2.539762,1.283673,no,Public_Transportation
1489,Female,41.318302,1.544937,77.053948,yes,yes,2.000000,3.000000,Sometimes,no,2.090413,no,0.000000,0.000000,Sometimes,Automobile
1214,Female,25.706285,1.585547,80.351263,yes,yes,2.000000,1.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation
1372,Male,20.580984,1.798354,103.705418,yes,yes,2.000000,3.000000,Sometimes,no,2.401315,no,2.891986,0.000000,no,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,Female,21.996118,1.730199,78.997062,yes,yes,2.277077,1.000000,Sometimes,no,2.000000,no,1.061743,0.000000,Sometimes,Public_Transportation
1168,Male,22.649792,1.685045,81.022119,yes,yes,2.000000,2.756622,Sometimes,no,1.606076,no,0.432973,1.749586,no,Public_Transportation
945,Male,23.455324,1.702516,75.000000,yes,yes,2.162519,3.000000,Sometimes,no,2.152666,no,1.078074,1.502839,Sometimes,Public_Transportation
1596,Male,22.906342,1.755902,120.021161,yes,yes,2.971574,2.807420,Sometimes,no,1.962646,no,1.583832,0.504816,Sometimes,Public_Transportation
607,Male,18.424941,1.753389,54.121925,yes,yes,2.000000,3.166450,Sometimes,no,2.278578,no,1.838881,2.000000,Sometimes,Public_Transportation

In [14]:
y_train

1661        Obesity_Type_II
715     Insufficient_Weight
1257         Obesity_Type_I
1737        Obesity_Type_II
829      Overweight_Level_I
               ...
2103       Obesity_Type_III
626     Insufficient_Weight
1863       Obesity_Type_III
1330         Obesity_Type_I
2055       Obesity_Type_III
Name: NObeyesdad, Length: 1477, dtype: object

In [15]:
# Create pipleline

# num_pipeline

num_pipeline = Pipeline(
                steps=[
                    ('imputer' , SimpleImputer(strategy='median')),
                    ('scaler' , StandardScaler())
                ])

cat_pipeline = Pipeline(
                steps=[
                    ('imputer', SimpleImputer(strategy = 'most_frequent')),
                    ('one_encoder' ,OneHotEncoder(sparse=False ,handle_unknown='ignore')),
                    ('scaler' , StandardScaler())
                    
                ])

preprocessor=ColumnTransformer(
    [
('num_pipeline',num_pipeline,num_cols),
('cat_pipeline',cat_pipeline,cat_cols)

]
)

In [16]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [17]:
models = {
    "logistic" : LogisticRegression(),
    'SVC' : SVC(),
    'Random' : RandomForestClassifier(),
    'Tree' : DecisionTreeClassifier()
}

In [18]:
# model create 
def evaluate_model(X_train,X_test , y_train,y_test , models):
    
    for i in range(len(models)):
        model =list(models.values())[i]
        model.fit(X_train ,y_train)

        # predict
        y_pred = model.predict(X_test)


        print(f'Model Name: {model}')
        print('---------------------------------------------------------------------')

        print(f'Accuracy Score: {accuracy_score(y_pred , y_test)}')

        print(f'\nClassification Report:\n {classification_report(y_pred,y_test)}')

        print('                                       ----------------------------------------------')

In [19]:
evaluate_model(X_train,X_test,y_train,y_test,models)

Model Name: LogisticRegression()
---------------------------------------------------------------------
Accuracy Score: 0.8722397476340694

Classification Report:
                      precision    recall  f1-score   support

Insufficient_Weight       0.99      0.85      0.91        92
      Normal_Weight       0.62      0.91      0.74        66
     Obesity_Type_I       0.93      0.92      0.93       108
    Obesity_Type_II       0.98      0.96      0.97        92
   Obesity_Type_III       1.00      0.98      0.99        96
 Overweight_Level_I       0.84      0.72      0.77        93
Overweight_Level_II       0.75      0.77      0.76        87

           accuracy                           0.87       634
          macro avg       0.87      0.87      0.87       634
       weighted avg       0.89      0.87      0.88       634

                                       ----------------------------------------------
Model Name: SVC()
---------------------------------------------------------------------
Accuracy Score: 0.8343848580441641

Classification Report:
                      precision    recall  f1-score   support

Insufficient_Weight       0.89      0.86      0.87        81
      Normal_Weight       0.69      0.65      0.67       102
     Obesity_Type_I       0.89      0.90      0.89       105
    Obesity_Type_II       0.98      0.92      0.95        96
   Obesity_Type_III       1.00      0.99      0.99        95
 Overweight_Level_I       0.72      0.73      0.73        79
Overweight_Level_II       0.66      0.78      0.72        76

           accuracy                           0.83       634
          macro avg       0.83      0.83      0.83       634
       weighted avg       0.84      0.83      0.84       634

                                       ----------------------------------------------
Model Name: RandomForestClassifier()
---------------------------------------------------------------------
Accuracy Score: 0.9495268138801262

Classification Report:
                      precision    recall  f1-score   support

Insufficient_Weight       0.95      0.97      0.96        77
      Normal_Weight       0.93      0.82      0.87       108
     Obesity_Type_I       0.97      0.98      0.98       105
    Obesity_Type_II       0.99      1.00      0.99        89
   Obesity_Type_III       1.00      1.00      1.00        94
 Overweight_Level_I       0.91      0.96      0.94        76
Overweight_Level_II       0.89      0.93      0.91        85

           accuracy                           0.95       634
          macro avg       0.95      0.95      0.95       634
       weighted avg       0.95      0.95      0.95       634

                                       ----------------------------------------------
Model Name: DecisionTreeClassifier()
---------------------------------------------------------------------
Accuracy Score: 0.9321766561514195

Classification Report:
                      precision    recall  f1-score   support

Insufficient_Weight       0.90      0.91      0.90        78
      Normal_Weight       0.86      0.86      0.86        96
     Obesity_Type_I       0.95      0.94      0.94       108
    Obesity_Type_II       0.99      0.98      0.98        91
   Obesity_Type_III       1.00      1.00      1.00        94
 Overweight_Level_I       0.91      0.87      0.89        84
Overweight_Level_II       0.90      0.96      0.93        83

           accuracy                           0.93       634
          macro avg       0.93      0.93      0.93       634
       weighted avg       0.93      0.93      0.93       634

                                       ----------------------------------------------